name: Taisei Yasui
permalink: :year/:month/:day/:title
baseurl: /TIL_pages

# Your blog's start year and this year, showed in the footer left
# start is optional
start: 2021
now: 2022
 
# Social links showed in the footer
# You just need modify the nickname of github and twitter
link:
  email : yasui-edu0834@toki.waseda.jp
  github : taisei-13046

# Links in the navigation, you can modify both link name and link url
nav:
   Home: "/"
   Posts: "/posts"
#    Profile: "/profile"
#    Products: "/products"

   
markdown: kramdown
highlighter: rouge

sass:
  sass_dir: _sass
  style: compressed
